// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHf2xvHa43mdvzEVbOiZcIwpDewDFeDdk',
    appId: '1:966446884402:web:117a8d5d8f781c498cfe2b',
    messagingSenderId: '966446884402',
    projectId: 'flashcard-app-v2-b0aa3',
    authDomain: 'flashcard-app-v2-b0aa3.firebaseapp.com',
    storageBucket: 'flashcard-app-v2-b0aa3.firebasestorage.app',
    measurementId: 'G-WH0JDMVJK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPlNJ9eq2XfAH-kQqtfM0cBPL8B_Nl3yM',
    appId: '1:966446884402:android:335e10f4b53b730b8cfe2b',
    messagingSenderId: '966446884402',
    projectId: 'flashcard-app-v2-b0aa3',
    storageBucket: 'flashcard-app-v2-b0aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzuLAQGqvteuZKqyz6o49IOTpR-7XPxUc',
    appId: '1:966446884402:ios:b6b98ef3ab0fe3c88cfe2b',
    messagingSenderId: '966446884402',
    projectId: 'flashcard-app-v2-b0aa3',
    storageBucket: 'flashcard-app-v2-b0aa3.firebasestorage.app',
    iosBundleId: 'com.example.flashcardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzuLAQGqvteuZKqyz6o49IOTpR-7XPxUc',
    appId: '1:966446884402:ios:b6b98ef3ab0fe3c88cfe2b',
    messagingSenderId: '966446884402',
    projectId: 'flashcard-app-v2-b0aa3',
    storageBucket: 'flashcard-app-v2-b0aa3.firebasestorage.app',
    iosBundleId: 'com.example.flashcardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHf2xvHa43mdvzEVbOiZcIwpDewDFeDdk',
    appId: '1:966446884402:web:bbd247b74d27f0b98cfe2b',
    messagingSenderId: '966446884402',
    projectId: 'flashcard-app-v2-b0aa3',
    authDomain: 'flashcard-app-v2-b0aa3.firebaseapp.com',
    storageBucket: 'flashcard-app-v2-b0aa3.firebasestorage.app',
    measurementId: 'G-Y1RGCVTGZ7',
  );
}
